# Generated by Django 3.2.7 on 2021-09-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Покупателя',
                'verbose_name_plural': 'Покупатель',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=200, verbose_name='Сорт')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('size', models.CharField(default='0', max_length=50, verbose_name='Размер цветка')),
                ('florescence', models.CharField(default='', max_length=200, verbose_name='Цветение')),
                ('delivery', models.CharField(blank=True, default='', max_length=200, verbose_name='Доставка')),
                ('main_photo', models.ImageField(upload_to='images/', verbose_name='Основное фото цветка')),
                ('description', models.CharField(blank=True, default='', max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветок',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название рода')),
            ],
            options={
                'verbose_name': 'Род',
                'verbose_name_plural': 'Род',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('AV', 'доступно'), ('EN', 'закончилось'), ('RE', 'на размножении')], default='AV', max_length=2, verbose_name='Доступность')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.flower', verbose_name='Цветок')),
            ],
            options={
                'verbose_name': 'Позицию',
                'verbose_name_plural': 'Позиция',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField(default=0, verbose_name='Сумма заказа')),
                ('prepayment', models.IntegerField(default=0, verbose_name='Предоплата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='SupplySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Размер поставки')),
            ],
            options={
                'verbose_name': 'Размер поставки',
                'verbose_name_plural': 'Размер поставки',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Доступное количество')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название вида')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.genus', verbose_name='Род')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Вид',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позицию заказа',
                'verbose_name_plural': 'Позиция заказа',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='supply_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.supplysize', verbose_name='Размер поставки'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.flower', verbose_name='Цветок')),
            ],
            options={
                'verbose_name': 'Картинку',
                'verbose_name_plural': 'Картинка',
            },
        ),
        migrations.AddField(
            model_name='flower',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.species', verbose_name='Вид'),
        ),
    ]
