# Generated by Django 3.2.7 on 2021-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='size',
            field=models.CharField(choices=[('Маленький, 10-15', '10-15'), ('Средний, 15-20', '15-20'), ('Большой, 20-25', '20-25')], default='small', max_length=20, verbose_name='Размер цветка'),
        ),
    ]
